# Generated by Django 2.0.5 on 2018-05-21 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emplyee',
            new_name='Employee',
        ),
    ]
